### ISSUE TITLE
Not able to import library

### ISSUE THREAD

**Issue by Nando-Cardoso** [voidburn/cron-expression-descriptor#2]
Hello, I've been trying to use this library but I don't know how to import it. I already modified my build.gradle and added everything but how can I make the import in my code?

**Comment by voidburn** [comment]
What IDE or Editor are you using? Intellij should offer to import missing classes (assuming the project is correctly set up), and so would Eclipse.

Assuming you will attempt to catch possible parse errors, you would at least need these imports:

```
import it.burning.cron.CronExpressionDescriptor;
import it.burning.cron.CronExpressionParser.CronExpressionParseException;
```

**Comment by Nando-Cardoso** [comment]
I Just managed to get it to work with the imports above, thank you so much for the help.
