### ISSUE TITLE
config   Locale  "zh"   result   error

### ISSUE THREAD

**Issue by iceMr** [voidburn/cron-expression-descriptor#3]
config   Locale  "zh"  
 
       CronExpressionDescriptor.setDefaultLocale("zh");
       CronExpressionDescriptor.getDescription("0-10 11 * * *");

       the result  is   å¨ %s å %s ä¹é´çæ¯åé   error

**Comment by voidburn** [comment]
I found an issue that prevented you to select language locales with more than 2 characters, so you can properly set "zh_CN". It should've defaulted to English though, not sure why you're getting that garbage out, maybe that's exactly the problem.

As for the incorrect encodings I can't help, I have no means to generate or test proper translations on many languages. The files are all UTF-8 encoded and can be decoded correctly as you can see in this preview here: https://github.com/voidburn/cron-expression-descriptor/blob/master/src/main/resources/localization_zh_CN.properties

Check out for the next commit, it will include the fix, try and see if it works then if you set the locale this way: `CronExpressionDescriptor.setDefaultLocale("zh_CN");`

If it works I will create a new release.

**Comment by iceMr** [comment]
I  set config  ,
CronExpressionDescriptor.setDefaultLocale("zh_CN");  
but  no work  .

download res  ,  change some code  ,

ResourceBundle bundle =ResourceBundle.getBundle(LOCALIZATION_BUNDLE,Locale.CHINA);
new String(bundle.getString(resourceName).getBytes(StandardCharsets.ISO_8859_1), StandardCharsets.UTF_8) .
 
The result is correct .  i do not know  Is  idea  environment problem ,thanks .

**Comment by voidburn** [comment]
I'm going to introduce the ability to set the default locale via the `Locale` constants, so you can use them directly.

Ultimately, test and see what works for you, and if you find errors in the translation I welcome a pull request from you with a new `localization_zh_CN.properties` but, as far as IntelliJ Idea goes, I can't see the characters in the output either, unless I do as you did, and create a new string that first gets the resource string bytes as ISO_8859_1 and then converts them to UTF-8:

**[ Current ]**
![Screenshot 2022-04-28 145319](https://user-images.githubusercontent.com/1438321/165758563-d42223c6-6ae1-4835-a1df-ad15e33f2a4a.png)

![Screenshot 2022-04-28 145405](https://user-images.githubusercontent.com/1438321/165758577-6e6e3222-8623-41c1-b63f-36bbe1268cc0.png)

**[ After conversion ]**
![Screenshot 2022-04-28 150022](https://user-images.githubusercontent.com/1438321/165758613-56c54ad9-f8dc-4715-85c0-96453a643b32.png)

![Screenshot 2022-04-28 150100](https://user-images.githubusercontent.com/1438321/165758683-a402b07b-ca27-4461-b5b8-4005c2fd557a.png)

I can still see some errors in there, but I would need your help and expertise to find a solution, either a better localization or a working solution.

I'll be happy to include Chinese specific instructions if you find a way to make it work!

**Comment by iceMr** [comment]
OK  ,  thanks !
